#import "Comscore.h"
#import "Comscore-Swift.h" // Generated by Xcode for Swift interop

@implementation Comscore {
    ComscoreImpl *_impl;
}

- (instancetype)init {
    self = [super init];
    if (self) {
        _impl = [[ComscoreImpl alloc] init];
    }
    return self;
}

- (void)initialize:(NSString *)publisherId
   applicationName:(NSString *)applicationName
    autoUpdateMode:(NSString *)autoUpdateMode
autoUpdateIntervalSeconds:(double)autoUpdateIntervalSeconds
     childDirected:(BOOL)childDirected
    validationMode:(BOOL)validationMode
startOnlyWhenUIIsVisible:(BOOL)startOnlyWhenUIIsVisible
    initialConsent:(NSString *)initialConsent
         debugLogs:(BOOL)debugLogs
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject {
    [_impl initializeWithPublisherId:publisherId
                     applicationName:applicationName
                      autoUpdateMode:autoUpdateMode
           autoUpdateIntervalSeconds:autoUpdateIntervalSeconds
                       childDirected:childDirected
                      validationMode:validationMode
            startOnlyWhenUIIsVisible:startOnlyWhenUIIsVisible
                      initialConsent:initialConsent
                           debugLogs:debugLogs
                             resolve:resolve
                              reject:reject];
}

- (void)notifyUxActive:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject {
    [_impl notifyUxActiveWithResolve:resolve reject:reject];
}

- (void)notifyUxInactive:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject {
    [_impl notifyUxInactiveWithResolve:resolve reject:reject];
}

- (void)trackSection:(NSString *)sectionName
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject {
    [_impl trackSectionWithSectionName:sectionName resolve:resolve reject:reject];
}

- (void)updateConsent:(NSString *)value
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject {
    [_impl updateConsentWithValue:value resolve:resolve reject:reject];
}

- (void)setChildDirected:(BOOL)enabled
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject {
    [_impl setChildDirectedWithEnabled:enabled resolve:resolve reject:reject];
}

- (void)setValidationMode:(BOOL)enabled
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject {
    [_impl setValidationModeWithEnabled:enabled resolve:resolve reject:reject];
}

- (void)getVersion:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject {
    [_impl getVersionWithResolve:resolve reject:reject];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeComscoreSpecJSI>(params);
}

@end
